[package]
name = "bsky-ai-tribalism-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.23"
rusqlite = "0.37.0"
serde = "1.0.225"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
